// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "alltube02-20181218104045-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://alltube02-20181218104045-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:8e3d59b7-9395-4117-a472-16399f5d9b94",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Zdw4yIM6E",
    "aws_user_pools_web_client_id": "1jj7ga64a5um4p6m2d0pimuuj9",
    "aws_user_files_s3_bucket": "alltube02ebd2b38e5ea44a268b37d878ce924fca",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://3jvtrk4b5bdgdlkga357b556nm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
